### ISSUE TITLE
希望可以改一下绿色主题标题栏顶部的小黑条和底部的小绿条

### ISSUE THREAD

**Issue by 26071violet** [Achuan-2/siyuan-themes-tsundoku#132]
![Image](https://github.com/user-attachments/assets/b67f1aa9-a236-4c9c-8460-3c24a825ee8c)

希望可以把小黑条隐藏掉，弄好我请主包吃辣条哦！

ps.主包的前端样式是我最满意的一个主题😚😚

**Comment by musnows** [comment]
思源笔记设置里面添加css代码片段

```css
/* 去掉底部绿条 */
.layout-tab-bar .item--focus::after {
  height: 0px;
}
/* 去掉顶部黑线 */
.layout__wnd--active .layout-tab-bar .item--focus, .b3-dialog__container .layout-tab-bar .item--focus {
  box-shadow: inset 0 0px 0 0 var(--custom-tab-focus-top-border) !important
}
```

<img width="364" alt="Image" src="https://github.com/user-attachments/assets/f4814324-e1ff-421f-bbd8-4e7ba13a9954" />
