### ISSUE TITLE
任务列表的样式不会加上删除线

### ISSUE THREAD

**Issue by QQQOrange** [Achuan-2/siyuan-themes-tsundoku#97]
加上删除线

**Comment by Achuan-2** [comment]
个人不喜欢添加删除线
需要的话可以在设置-外观-代码片段添加css片段
```css
.protyle-wysiwyg .protyle-task--done > div:not([data-subtype='t']) {
    text-decoration: line-through !important;
    color: var(--b3-theme-on-surface-light);
}
```
