### ISSUE TITLE
自定义字体的代码片段重启思源后失效

### ISSUE THREAD

**Issue by QQQOrange** [Achuan-2/siyuan-themes-tsundoku#99]
@font-face {
    font-family: "LXGW WenKai";
    font-style: normal;
    src: url("plugins/custom-fonts/static/fonts/Twemoji.Mozilla/LXGWWenKai-Regular.ttf");
}

:root {
    --b3-font-family: "LXGW WenKai", "LXGW WenKai Screen R", "Helvetica Neue", "Luxi Sans", "DejaVu Sans", "Hiragino Sans GB", "Microsoft Yahei", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", "Segoe UI Symbol", "Android Emoji", "EmojiSymbols";
    --b3-font-family-code: "LXGW WenKai", "LXGW WenKai Screen R", "JetBrainsMono-Regular", "mononoki", "Consolas", "Liberation Mono", "Menlo", "Courier", "monospace", "Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", "Segoe UI Symbol", "Android Emoji", "EmojiSymbols";
    --b3-font-family-graph: "LXGW WenKai", "LXGW WenKai Screen R", "mononoki";
    --b3-font-family-math: "LXGW WenKai", "LXGW WenKai Screen R", "KaTeX_Math", "KaTeX_Main";
}

以上是代码片段，在默认主题下重启仍然生效，使用積読主题下需要先关闭在开启该代码片段才能生效。

**Comment by Achuan-2** [comment]
其他主题也有这个问题吗，可能和代码片段与主题css加载顺序有关

**Comment by QQQOrange** [comment]
> 其他主题也有这个问题吗，可能和代码片段与主题css加载顺序有关

其他的主题没有啊，例如savor

**Comment by QQQOrange** [comment]
> 其他主题也有这个问题吗，可能和代码片段与主题css加载顺序有关

准确的说，其他主题生效的情况下，切换到Tsundoku，就变成默认字体了

**Comment by Achuan-2** [comment]
我用汉仪空山楷字体是没问题的
```css

@font-face {
font-family: "汉仪空山楷";
font-style: normal;
src: url("plugins/custom-fonts/汉仪空山楷.ttf");
}

:root {
--b3-font-family: "汉仪空山楷", "Helvetica Neue", "Luxi Sans", "DejaVu Sans", "Hiragino Sans GB", "Microsoft Yahei", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", "Segoe UI Symbol", "Android Emoji", "EmojiSymbols";

}
```
首先你这个字体路径就不对吧
<img width="620" alt="Snipaste_2024-01-15_09-39-39" src="https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/60436214/5f5b9dc2-f152-4640-be8e-f92444e2b6b6">
